Repository rexor12/holobot, pull requests merged in 2022-08, with the labels that each got.

#138 Discord events and strip user permissions on leave
  holobot/discord/bot/bot_service.py
  holobot/discord/events/__init__.py
  holobot/discord/events/discord_event_listener_base.py
  holobot/discord/events/exception_event_listener.py
  holobot/discord/events/idiscord_event_listener.py
  holobot/discord/events/igeneric_discord_event_listener.py
  holobot/discord/events/interaction_created_event_listener.py
  holobot/discord/events/member_deleted_event_listener.py
  holobot/discord/events/started_event_listener.py
  holobot/discord/events/starting_event_listener.py
  holobot/discord/sdk/events/__init__.py
  holobot/discord/sdk/events/server_member_left_event.py
  holobot/extensions/moderation/enums/moderator_permission.py
  holobot/extensions/moderation/managers/ipermission_manager.py
  holobot/extensions/moderation/managers/permission_manager.py
  holobot/extensions/moderation/reactive/__init__.py
  holobot/extensions/moderation/reactive/strip_permissions_on_user_leave.py
Labels: enhancement

#140 Keep the old permissions when creating the Muted role
  holobot/discord/servers/managers/channel_manager.py
Labels: bug

#141 Implement listener priority for execution sequence control
  holobot/discord/events/member_deleted_event_listener.py
  holobot/discord/workflows/processors/command_processor.py
  holobot/discord/workflows/processors/component_processor.py
  holobot/discord/workflows/processors/menu_item_processor.py
  holobot/extensions/moderation/reactive/punish_on_enough_warns_accumulated.py
  holobot/extensions/moderation/reactive/strip_permissions_on_user_leave.py
  holobot/sdk/reactive/ilistener.py
Labels: enhancement

#149 Update dependencies
  requirements.txt
Labels: refactor

#155 Update VS Code workspace settings
  .vscode/settings.json
Labels: refactor

#160 Fix trigger time calculation, add a trace message
  holobot/extensions/giveaways/scraper_runner.py
  holobot/extensions/giveaways/scrapers/epic_games_scraper.py
Labels: bug, component: extension

#163 Fix weather I18N keys
  holobot/extensions/weather/workflows/get_basic_weather_workflow.py
Labels: bug, component: extension

#166 Try to respond with an error on unhandled exceptions
  holobot/discord/workflows/interaction_processor_base.py
  resources/i18n/default.json
Labels: enhancement, component: discord

#170 Add `Singleton` metaclass and `UNDEFINED` sentinel
  holobot/sdk/utils/__init__.py
  holobot/sdk/utils/type_utils.py
Labels: component: framework

#173 More refactors
  holobot/discord/bot/__init__.py
  holobot/discord/bot/bot_accessor.py
  holobot/discord/bot/bot_service.py
  holobot/discord/data_providers/bot_data_provider.py
  holobot/discord/data_providers/emoji_data_provider.py
  holobot/discord/data_providers/user_data_provider.py
  holobot/discord/messaging.py
  holobot/discord/sdk/actions/content_changing_action_base.py
  holobot/discord/sdk/models/embed.py
  holobot/discord/sdk/workflows/interactables/components/combo_box.py
  holobot/discord/sdk/workflows/interactables/components/layout.py
  holobot/discord/sdk/workflows/interactables/components/models/combo_box_state.py
  holobot/discord/servers/managers/channel_manager.py
  holobot/discord/servers/managers/role_manager.py
  holobot/discord/servers/member_data_provider.py
  holobot/discord/utils/bot_utils.py
Labels: enhancement

#177 Fix typing
  holobot/sdk/caching/concurrent_cache.py
  holobot/sdk/utils/__init__.py
  holobot/sdk/utils/type_utils.py
Labels: bug

#175 Rewrite version generator
  .github/workflows/assign_version.yml
  VERSION
  generate_version.py
  generate_version.sh
  holobot/framework/system/environment.py
  holobot/sdk/system/models/version.py
Labels: component: framework, devops

#180 Remove `applications.commands` scope
  README.md
Labels: documentation, technical

#181 Fix markdown for inline codeblocks
  holobot/discord/sdk/models/reaction.py
  holobot/sdk/database/queries/query.py
Labels: documentation

#183 Replace user mutes with time-out
  config.json
  holobot/discord/sdk/servers/managers/__init__.py
  holobot/discord/sdk/servers/managers/iuser_manager.py
  holobot/discord/servers/managers/user_manager.py
  holobot/extensions/moderation/__init__.py
  holobot/extensions/moderation/constants.py
  holobot/extensions/moderation/database/mutes_migration.py
  holobot/extensions/moderation/managers/__init__.py
  holobot/extensions/moderation/managers/imute_manager.py
  holobot/extensions/moderation/managers/mute_manager.py
  holobot/extensions/moderation/models/__init__.py
  holobot/extensions/moderation/models/mute.py
  holobot/extensions/moderation/mute_cleanup_processor.py
  holobot/extensions/moderation/reactive/punish_on_enough_warns_accumulated.py
  holobot/extensions/moderation/repositories/__init__.py
  holobot/extensions/moderation/repositories/imutes_repository.py
  holobot/extensions/moderation/repositories/mutes_repository.py
  holobot/extensions/moderation/workflows/mute_user_workflow.py
  holobot/extensions/moderation/workflows/unmute_user_workflow.py
Labels: component: discord, component: extension, feature request

#184 Implement "/moderation permissions view" command
  config.json
  holobot/extensions/dev/workflows/show_available_servers_workflow.py
  holobot/extensions/moderation/repositories/iuser_repository.py
  holobot/extensions/moderation/repositories/user_repository.py
  holobot/extensions/moderation/workflows/__init__.py
  holobot/extensions/moderation/workflows/view_user_permissions_workflow.py
  holobot/sdk/queries/pagination_result.py
  holobot/sdk/utils/__init__.py
  holobot/sdk/utils/pagination_utils.py
  resources/i18n/default.json
Labels: component: extension, feature request

#186 Implement reactions
  .vscode/launch.json
  config.json
  holobot/discord/sdk/models/interaction_context.py
  holobot/discord/sdk/workflows/workflow_base.py
  holobot/extensions/crypto/crypto_updater.py
  holobot/extensions/general/api_clients/__init__.py
  holobot/extensions/general/api_clients/dtos/__init__.py
  holobot/extensions/general/api_clients/dtos/waifu_pics_batch_result.py
  holobot/extensions/general/api_clients/iwaifu_pics_client.py
  holobot/extensions/general/api_clients/waifu_pics_client.py
  holobot/extensions/general/providers/__init__.py
  holobot/extensions/general/providers/ireaction_provider.py
  holobot/extensions/general/providers/reaction_provider.py
  holobot/extensions/general/workflows/__init__.py
  holobot/extensions/general/workflows/react_workflow.py
  holobot/extensions/giveaways/scrapers/epic_games_scraper.py
  holobot/extensions/google/google_client.py
  holobot/extensions/weather/weather_client.py
  holobot/sdk/network/resilience/__init__.py
  holobot/sdk/network/resilience/async_circuit_breaker.py
  holobot/sdk/network/resilience/async_rate_limiter.py
  holobot/sdk/network/resilience/exceptions/__init__.py
  holobot/sdk/network/resilience/exceptions/rate_limited_error.py
  holobot/sdk/utils/__init__.py
  holobot/sdk/utils/dict_utils.py
  resources/i18n/default.json
Labels: component: extension, feature request

#187 Implement cooldowns, configure interactables
  holobot/discord/sdk/events/command_processed_event.py
  holobot/discord/sdk/events/component_processed_event.py
  holobot/discord/sdk/events/menu_item_processed_event.py
  holobot/discord/sdk/workflows/interactables/decorators/command.py
  holobot/discord/sdk/workflows/interactables/decorators/component.py
  holobot/discord/sdk/workflows/interactables/decorators/menu_item.py
  holobot/discord/sdk/workflows/interactables/enums/__init__.py
  holobot/discord/sdk/workflows/interactables/enums/entity_type.py
  holobot/discord/sdk/workflows/interactables/interactable.py
  holobot/discord/sdk/workflows/interactables/models/__init__.py
  holobot/discord/sdk/workflows/interactables/models/cooldown.py
  holobot/discord/sdk/workflows/rules/iworkflow_execution_rule.py
  holobot/discord/workflows/__init__.py
  holobot/discord/workflows/events/__init__.py
  holobot/discord/workflows/events/interactable_processed_event_listener.py
  holobot/discord/workflows/iinvocation_tracker.py
  holobot/discord/workflows/interaction_processor_base.py
  holobot/discord/workflows/invocation_tracker.py
  holobot/discord/workflows/processors/command_processor.py
  holobot/discord/workflows/processors/component_processor.py
  holobot/discord/workflows/processors/menu_item_processor.py
  holobot/discord/workflows/rules/__init__.py
  holobot/discord/workflows/rules/has_required_permissions_rule.py
  holobot/discord/workflows/rules/is_interactable_available_for_server_rule.py
  holobot/discord/workflows/rules/is_interactable_on_cooldown_rule.py
  holobot/extensions/admin/workflows/rules/halt_disabled_commands_rule.py
  holobot/extensions/general/workflows/magic_eight_ball_workflow.py
  holobot/extensions/general/workflows/react_workflow.py
  holobot/extensions/general/workflows/roll_number_workflow.py
  holobot/extensions/general/workflows/summon_user_workflow.py
  holobot/extensions/giveaways/workflows/view_active_giveaways_workflow.py
  holobot/extensions/google/workflows/search_google_workflow.py
  holobot/extensions/moderation/reactive/log_on_moderation_command_used.py
  holobot/extensions/moderation/reactive/log_on_moderation_menu_item_used.py
  holobot/extensions/moderation/reactive/punish_on_enough_warns_accumulated.py
  holobot/extensions/moderation/workflows/rules/check_moderator_permission_rule.py
  holobot/extensions/reminders/workflows/set_reminder_workflow.py
  holobot/extensions/reminders/workflows/view_reminders_workflow.py
  holobot/extensions/server/workflows/view_server_banner_workflow.py
  holobot/extensions/server/workflows/view_server_icon_workflow.py
  holobot/extensions/todo_lists/workflows/add_todo_item_workflow.py
  holobot/extensions/todo_lists/workflows/view_todo_items_workflow.py
  holobot/sdk/caching/concurrent_cache.py
  holobot/sdk/utils/type_utils.py
  resources/i18n/default.json
Labels: component: discord, component: extension, feature request
